# -*- coding: utf-8 -*-
"""python_fundametals_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fu_PKDA6hUrBthjbC8pjWrKtB7SNi9if

# Python fundamentals Assignment

Exercise 1
"""

#code to print name, student number and email.

#name
print("Subuhan P. Ummer")

#student number
print("DSML3645")

#email address
print("subuhanpummer@gmail.com")

"""Exercise 2"""

#code to print name, student number and email using escape sequence.

print("Subuhan P. Ummer \nDSML3645 \nsubuhanpummer@gmail.con")

"""Exercise 3"""

#code that add, subract, multiply and divide two numbers.

a = 8
b = 16

#add
print(f"{a} + {b} = {a + b}")

#subtract
print(f"{a} - {b} = {a - b}")

#multiply
print(f"{a} x {b} = {a * b}")

#division
print(f"{a} / {b} = {a / b}")

"""Exercise 4"""

#code to displays numbers from 1 to 5 as steps.

for i in range(1, 6):
    print(i)

"""Exercise 5"""

#code to output the sentence with quotes and a line break.

print('"SDE" stands for "Software Development Kit", whereas\n"IDE" stands for "integrated Development Environment".')

"""Exercise 6"""

#practice print statements.

print("python is an \"awesome\" language.")
print("python\n\t2023")
print('I\'m from Entri.\b')
print("\65")
print("\x65")
print("Entri", "2023", sep="\n")
print("Entri", "2023", sep="\b")
print("Entri", "2023", sep="*", end="\b\b\b\b")

"""Exercise 7"""

#types of each variables.
num=23
textnum="57"
decimal=98.3

print("type of num is : ",type(num))
print("type of textnum is : ", type(textnum))
print("type of decimal is : ", type(decimal))

#sum of variables
sum = num+int(textnum)+decimal
print("sum of variables is : ", sum)

#datatype of sum
print("datatype of sum is : ", type(sum))

"""Exercise 8"""

#number of minutes in a year using variables.

days_in_year = 365
hours_in_day = 24
minutes_in_hour = 60

minutes_in_year = days_in_year * hours_in_day * minutes_in_hour

print(f"Total number of minutes in a year is : {minutes_in_year} minutes")

"""Exercise 9"""

#code to greet user with theri name.

name = input("Please enter your name: ")

print(f"Hi {name}, welcome to Python programming :)")

"""Exercise 10"""

#code to convert pounds to dollars

pounds = float(input("Please enter amount in pounds (£): "))
dollars = pounds * 1.31 #conversion rate is £1 = $1.31
print(f"£{pounds} are ${dollars:.2f}")

